version: "3"

services:

    jenkins:
        image: jenkins/jenkins:lts-jdk11
        container_name: mijenkins
        ports:
            - 8080:8080 
            - 50000:50000
        restart: on-failure     # Arranque de Jenkins con la máquina y si se cae
        user: root              # Para poder crear contenedores
        volumes:
            - /home/ubuntu/environment/datos/jenkins:/var/jenkins_home 
#            - /var/jenkins_home :/var/jenkins_home             # Esta es la buena
            # DiD: Docker In Docker            
            - /var/run/docker.sock:/var/run/docker.sock # Le inyecto el socket de comunicación con el demonio de dockerd
            - /usr/bin/docker:/usr/bin/docker           # Le inyecto el binario de docker

            # TOKEN PARA SONAR: 11aceed334098a92bf23631cc0085db2ad