# Al utilizar sonar internamente ELASTICSEARCH, necesita esta configuración:
#sysctl -w vm.max_map_count=524288
#sysctl -w fs.file-max=131072
#ulimit -n 131072
#ulimit -u 8192

version: "3"

services:

  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/ubuntu/environment/datos/sonar/data:/opt/sonarqube/data
      - /home/ubuntu/environment/datos/sonar/extensions:/opt/sonarqube/extensions
      - /home/ubuntu/environment/datos/sonar/logs:/opt/sonarqube/logs
    ports:
      - "8081:9000"
      
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - /home/ubuntu/environment/datos/postgresql/core:/var/lib/postgresql
      - /home/ubuntu/environment/datos/postgresql/data:/var/lib/postgresql/data

# Esto no me interesa
#volumes:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  postgresql:
#  postgresql_data:

# docker-compose -f sonar.yaml up

# Token SONAR: squ_6649d7388cf3b9978565c36e86cb4c46cae7aaf3